services:
  receiver:
    environment:
      - CONFIG_FILE=/app/config/prod/receiver_conf.yml
      - LOG_FILE=/logs/receiver.log
      - LOG_CONFIG_FILE=/app/config/prod/log_conf.yml
    restart: always

  storage:
    environment:
      - CONFIG_FILE=/app/config/prod/storage_conf.yml
      - LOG_FILE=/logs/storage.log
      - LOG_CONFIG_FILE=/app/config/prod/log_conf.yml
      - STORAGE_USER=${STORAGE_USER}
      - STORAGE_PASSWORD=${STORAGE_PASSWORD}
    restart: always

  processing:
    environment:
      - CONFIG_FILE=/app/config/prod/processing_conf.yml
      - LOG_FILE=/logs/processing.log
      - LOG_CONFIG_FILE=/app/config/prod/log_conf.yml
    restart: always

  consistency:
    environment:
      - LOG_FILE=/logs/consistency.log
      - LOG_CONFIG_FILE=/app/config/prod/log_conf.yml
    restart: always

  anomaly:
    environment:
      - CONFIG_FILE=/app/config/dev/anon_conf.yml
      - LOG_FILE=/logs/anomaly.log
      - LOG_CONFIG_FILE=/app/config/dev/log_conf.yml
      - ANON_WIND=60
      - ANON_TEMP=0
    restart: always


  analyzer:
    environment:
      - CONFIG_FILE=/app/config/prod/analyzer_conf.yml
      - LOG_FILE=/logs/analyzer.log
      - LOG_CONFIG_FILE=/app/config/prod/log_conf.yml
    restart: always
